application: wikilicious2
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "2h"

libraries:
- name: jinja2
  version: latest
- name: PIL
  version: latest


handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /static
  static_dir: static

- url: /fb_anfrage.*
  script: fb_anfrage.app

- url: /fb_anwaelte.*
  script: fb_anwaelte.app

- url: /fb_augarten.*
  script: fb_augarten.app

- url: /botendienst_fbconnect.*
  script: botendienst_fbconnect.app

- url: /botendienst.*
  script: fb_botendienst.app

- url: /wolfhesse.*
  script: wolfhesse_fbconnect.app

- url: /.*
  script: helloworld.app

